/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutPublicRouteImport } from './routes/_layout/_public'
import { Route as LayoutProtectedRouteImport } from './routes/_layout/_protected'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as LayoutPublicSignUpRouteImport } from './routes/_layout/_public/sign-up'
import { Route as LayoutPublicSignInRouteImport } from './routes/_layout/_public/sign-in'
import { Route as LayoutProtectedPostsPostIdRouteImport } from './routes/_layout/_protected/posts/$postId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPublicRoute = LayoutPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtectedRoute = LayoutProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPublicSignUpRoute = LayoutPublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicSignInRoute = LayoutPublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutProtectedPostsPostIdRoute =
  LayoutProtectedPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => LayoutProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/sign-in': typeof LayoutPublicSignInRoute
  '/sign-up': typeof LayoutPublicSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/posts/$postId': typeof LayoutProtectedPostsPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/sign-in': typeof LayoutPublicSignInRoute
  '/sign-up': typeof LayoutPublicSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/posts/$postId': typeof LayoutProtectedPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_protected': typeof LayoutProtectedRouteWithChildren
  '/_layout/_public': typeof LayoutPublicRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_public/sign-in': typeof LayoutPublicSignInRoute
  '/_layout/_public/sign-up': typeof LayoutPublicSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_layout/_protected/posts/$postId': typeof LayoutProtectedPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/posts/$postId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_protected'
    | '/_layout/_public'
    | '/_layout/about'
    | '/_layout/'
    | '/_layout/_public/sign-in'
    | '/_layout/_public/sign-up'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_layout/_protected/posts/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_public': {
      id: '/_layout/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_protected': {
      id: '/_layout/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutProtectedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_public/sign-up': {
      id: '/_layout/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof LayoutPublicSignUpRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/sign-in': {
      id: '/_layout/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof LayoutPublicSignInRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_protected/posts/$postId': {
      id: '/_layout/_protected/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof LayoutProtectedPostsPostIdRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
  }
}

interface LayoutProtectedRouteChildren {
  LayoutProtectedPostsPostIdRoute: typeof LayoutProtectedPostsPostIdRoute
}

const LayoutProtectedRouteChildren: LayoutProtectedRouteChildren = {
  LayoutProtectedPostsPostIdRoute: LayoutProtectedPostsPostIdRoute,
}

const LayoutProtectedRouteWithChildren = LayoutProtectedRoute._addFileChildren(
  LayoutProtectedRouteChildren,
)

interface LayoutPublicRouteChildren {
  LayoutPublicSignInRoute: typeof LayoutPublicSignInRoute
  LayoutPublicSignUpRoute: typeof LayoutPublicSignUpRoute
}

const LayoutPublicRouteChildren: LayoutPublicRouteChildren = {
  LayoutPublicSignInRoute: LayoutPublicSignInRoute,
  LayoutPublicSignUpRoute: LayoutPublicSignUpRoute,
}

const LayoutPublicRouteWithChildren = LayoutPublicRoute._addFileChildren(
  LayoutPublicRouteChildren,
)

interface LayoutRouteChildren {
  LayoutProtectedRoute: typeof LayoutProtectedRouteWithChildren
  LayoutPublicRoute: typeof LayoutPublicRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProtectedRoute: LayoutProtectedRouteWithChildren,
  LayoutPublicRoute: LayoutPublicRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
